### ISSUE TITLE
File not found when downloading:

### ISSUE THREAD

**Issue by diabolical17** [gbl/CrowdinTranslate#1]
Exception when downloading translations via gradle
java.io.FileNotFoundException: https://crowdin.com/backend/download/project/aether.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1167)
	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.getCrowdinTranslations(CrowdinTranslate.java:155)
	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.run(CrowdinTranslate.java:124)

Result of web request: 
```json
{"success":false,"version":"9"}
```

**Comment by diabolical17** [comment]
Also happens on minecraft launch:

```logs
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: Exception when downloading translations
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: java.io.FileNotFoundException: https://crowdin.com/backend/download/project/aether.zip
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.net.URL.openStream(URL.java:1167)
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.getCrowdinTranslations(CrowdinTranslate.java:155)
[16:05:51] [Thread-1/INFO] (Minecraft) [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.run(CrowdinTranslate.java:124)
```

**Comment by diabolical17** [comment]
Nevermind found the error, i hadn't built the project on crowdin

**Comment by gbl** [comment]
You need to build the project once to get a zip to download. In your project, press the "Settings" button to the top right (below your avatar icon), there, you'll find the green "Build & Download" button.

You can either press that button and ignore the download file, or press the arrow, then "Build Project".

After that, the download should work.

Oh yeah. You found it while I was typing.
